# Generated by Django 5.1.6 on 2025-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre Usuario', models.TextField(blank=True, max_length=100, null=True)),
                ('Apellido Usuario', models.TextField(blank=True, max_length=100, null=True)),
                ('Alias Usuario', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
